#!/usr/bin/env python3
"""
Builds INDEX.md -- the searchable catalogue of every solved problem -- by
reading the @tag metadata block at the top of each solution file.

Every solution file carries a header like:

    @platform   LeetCode
    @id         1
    @title      Two Sum
    @difficulty Easy
    @topics     Array, Hash Table
    @pattern    Brute-Force Pair Scan
    @url        https://leetcode.com/problems/two-sum/

This script parses those, writes INDEX.md, and refreshes the TOPICS block in
README.md. Pure stdlib -- no dependencies, safe to run in CI.
"""

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOLUTION_DIRS = ["LeetCode", "CodeChef"]
SOLUTION_SUFFIXES = {".cpp", ".py", ".java", ".js", ".c", ".go", ".rs", ".kt", ".ts"}

LANG_NAMES = {
    ".cpp": "C++", ".py": "Python", ".java": "Java", ".js": "JavaScript",
    ".c": "C", ".go": "Go", ".rs": "Rust", ".kt": "Kotlin", ".ts": "TypeScript",
}

DIFFICULTY_ICON = {"easy": "\U0001F7E2", "medium": "\U0001F7E1", "hard": "\U0001F534"}

# Accepts both "@topics Array, Math" and "@topics : Array, Math". The colon
# form is what the generator sometimes emits, and without tolerating it the
# colon ends up glued to every value -- producing links like "(: https://...)"
# and a difficulty of ": Easy".
TAG_RE = re.compile(r"@(\w+)\s*:?\s+(.*?)\s*$")
DECORATION_RE = re.compile(r"^(\*|#|//|/\*)+\s*")
STEM_RE = re.compile(r"^(\d+)[.\-_ ]+(.*)$")


def parse_header(path):
    """Pull the @tag block out of a solution file's leading comment."""
    meta = {}
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()[:60]
    except OSError:
        return meta

    for raw in lines:
        # Strip whatever comment decoration the language uses.
        line = DECORATION_RE.sub("", raw.strip()).strip()
        match = TAG_RE.search(line)
        if match:
            key, value = match.group(1).lower(), match.group(2).strip()
            if value:
                meta[key] = value
    return meta


def collect():
    """Walk the solution directories and return one record per solution file."""
    records = []
    for folder in SOLUTION_DIRS:
        base = ROOT / folder
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file() or path.suffix not in SOLUTION_SUFFIXES:
                continue

            meta = parse_header(path)
            rel = path.relative_to(ROOT).as_posix()

            # Fall back to the filename ("13.Roman_to_Integer.cpp") when a file
            # has no header yet, so nothing silently vanishes from the index.
            stem = path.stem
            fallback_id, fallback_title = "", stem.replace("_", " ")
            stem_match = STEM_RE.match(stem)
            if stem_match:
                fallback_id = stem_match.group(1)
                fallback_title = stem_match.group(2).replace("_", " ")

            raw_topics = meta.get("topics", "")
            topics = [t.strip() for t in re.split(r"[,|]", raw_topics) if t.strip()]

            records.append({
                "platform": meta.get("platform", folder),
                "id": meta.get("id", fallback_id),
                "title": meta.get("title", fallback_title),
                "difficulty": meta.get("difficulty", ""),
                "topics": topics or ["Uncategorised"],
                "pattern": meta.get("pattern", ""),
                "solved": meta.get("solved", ""),
                "url": meta.get("url", ""),
                "lang": LANG_NAMES.get(path.suffix, path.suffix.lstrip(".")),
                "path": rel,
                "documented": bool(raw_topics),
            })
    return records


def sort_key(record):
    """Group by platform, then numeric problem id where one exists."""
    try:
        num = int(record["id"])
    except (TypeError, ValueError):
        num = 10 ** 9
    return (record["platform"].lower(), num, record["title"].lower())


def diff_label(record):
    difficulty = record["difficulty"]
    if not difficulty:
        return "-"
    icon = DIFFICULTY_ICON.get(difficulty.lower(), "\U0001F539")
    return icon + " " + difficulty


def md_link(text, href):
    return "[" + text + "](" + href + ")" if href else text


def build_index(records):
    by_topic = defaultdict(list)
    for record in records:
        for topic in record["topics"]:
            by_topic[topic].append(record)

    platforms = defaultdict(int)
    for record in records:
        platforms[record["platform"]] += 1
    platform_line = " / ".join(
        "**{0}** {1}".format(k, v) for k, v in sorted(platforms.items())
    )

    out = []
    out.append("# \U0001F4DA Problem Index\n")
    out.append(
        "> Auto-generated by `scripts/build_index.py` from the `@tag` header of\n"
        "> every solution file. Do not edit by hand - changes are overwritten.\n"
    )
    out.append("\n**{0} problems solved** - {1}\n".format(len(records), platform_line))
    out.append("\n---\n")

    # ---------------- Master table ----------------
    out.append("\n## \U0001F5C2 All Problems\n")
    out.append("| # | Problem | Platform | Difficulty | Topics | Pattern | Lang | Solved | Solution |")
    out.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
    for record in sorted(records, key=sort_key):
        out.append("| {0} | {1} | {2} | {3} | {4} | {5} | {6} | {7} | [code]({8}) |".format(
            record["id"] or "-",
            md_link(record["title"], record["url"]),
            record["platform"],
            diff_label(record),
            ", ".join(record["topics"]),
            record["pattern"] or "-",
            record["lang"],
            record["solved"] or "-",
            record["path"],
        ))

    # ---------------- Grouped by topic ----------------
    out.append("\n---\n")
    out.append("\n## \U0001F3F7 By Topic\n")
    out.append(
        "The same problems grouped by the data structure or technique they\n"
        "exercise. Use this to drill one pattern instead of working in ID order.\n"
    )
    for topic in sorted(by_topic, key=lambda t: (-len(by_topic[t]), t)):
        rows = sorted(by_topic[topic], key=sort_key)
        out.append("\n### {0} ({1})\n".format(topic, len(rows)))
        for record in rows:
            label = "{0} {1}".format(record["platform"], record["id"]).strip()
            out.append("- **{0}** - {1} ({2}, {3}) -> [code]({4})".format(
                label,
                md_link(record["title"], record["url"]),
                diff_label(record),
                record["lang"],
                record["path"],
            ))

    # ---------------- Undocumented ----------------
    missing = [r for r in records if not r["documented"]]
    if missing:
        out.append("\n---\n")
        out.append("\n## ⚠️ Missing Explanations\n")
        out.append(
            "These files have no `@tag` header yet, so they are only partially\n"
            "classified above. Run `python scripts/process_inbox.py --fix` or\n"
            "`/solved` on them.\n"
        )
        for record in sorted(missing, key=sort_key):
            out.append("- [`{0}`]({0})".format(record["path"]))

    out.append("\n")
    return "\n".join(out)


def topic_table(records):
    counts = defaultdict(int)
    for record in records:
        for topic in record["topics"]:
            counts[topic] += 1

    lines = ["\n### \U0001F3F7 Topics Covered\n", "| Topic | Problems |", "| :--- | :---: |"]
    for topic, count in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append("| {0} | {1} |".format(topic, count))
    lines.append("\n> Full breakdown with links: **[INDEX.md](INDEX.md)**\n")
    return "\n".join(lines)


def replace_block(content, start, end, body):
    """Swap the text between two HTML-comment markers, if both are present."""
    if start not in content or end not in content:
        return content
    before = content.split(start)[0]
    after = content.split(end, 1)[1]
    return before + start + "\n" + body + "\n" + end + after


def main():
    records = collect()

    (ROOT / "INDEX.md").write_text(build_index(records), encoding="utf-8")
    print("INDEX.md written - {0} problems".format(len(records)))

    readme = ROOT / "README.md"
    if readme.exists():
        content = readme.read_text(encoding="utf-8")
        updated = replace_block(
            content, "<!-- TOPICS_START -->", "<!-- TOPICS_END -->", topic_table(records)
        )
        if updated != content:
            readme.write_text(updated, encoding="utf-8")
            print("README.md topics block refreshed")

    undocumented = [r["path"] for r in records if not r["documented"]]
    if undocumented:
        print("warning: {0} file(s) missing an @tag header:".format(len(undocumented)))
        for path in undocumented:
            print("  - " + path)


if __name__ == "__main__":
    main()
